version: "3.9"

services:
  db:
    container_name: api-virak-me-db
    image: mysql:8.0.32
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net

  api:
    container_name: api-virak-me
    build: .
    restart: always
    env_file:
      - .env
    environment:
      PORT: "${PORT}"
      DSN: "${DSN}"
      SECRET: "${SECRET}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
    expose:
      - ${PORT}
    depends_on:
      - db
    links:
      - db
    networks:
      - net

  nginx:
    container_name: api-virak-me-proxy
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - "${PORT}:${PORT}"
    networks:
      - net

volumes:
  mysql-data:

networks:
  net:
    driver: bridge
