name: CI PROD
run-name: ${{ github.actor }}
on:
  pull-request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test
        run: |
          ls -la
          cd src/utils
          go test -v

  build-docker-image:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .env
        run: |
          echo -e "PORT=${{ secrets.PORT }}\nDSN=${{ secrets.DSN }}\nSECRET=${{ secrets.secret }}" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DK_USERNAME }}
          password: ${{ secrets.DK_PASSWORD }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: web-app-api/${{ secrets.DK_USERNAME }}:latest
          secret-files: |
            "MY_SECRET=./.env"

  ssh-to-vm:
    needs: build-docker-image
    runs-on: ubuntu-22.04
    steps:
      - name: Start Login
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.VM_PORT }}
          script: |
            if [ -f "deployment.sh" ]; then rm -rf deployment.sh; else curl -LO https://raw.githubusercontent.com/virakkhun/api.virak.me/main/scripts/deployment.sh; fi;
            chmod u+x deployment.sh
            echo "everything is up and running..."
